Changes to launching the python.d plugin aggregator. (#6781)
* Changes to launching the python.d plugin aggregator.

Passing python.d arguments from netdata.conf

Path to the specific python interpreter can be passed on the command-line.
Reused existing configuration options, changed the plugin script to match. To
specify a python binary use the -p switch. The existing pythond options can
be passed in, for example:

[plugin:python.d]
        command options = -p/usr/local/bin/python2.7 trace debug

diff --git a/collectors/python.d.plugin/python.d.plugin.in b/collectors/python.d.plugin/python.d.plugin.in
--- a/collectors/python.d.plugin/python.d.plugin.in
+++ b/collectors/python.d.plugin/python.d.plugin.in
@@ -1,7 +1,21 @@
 #!/usr/bin/env bash
 '''':;
-exec "$(command -v python || command -v python3 || command -v python2 ||
-echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
+pybinary=$(which python || which python3 || which python2)
+filtered=()
+for arg in "$@"
+do
+    case $arg in
+        -p*) pybinary=${arg:2}
+              shift 1          ;;
+        *)  filtered+=("$arg") ;;
+    esac
+done
+if [ "$pybinary" = "" ]
+then
+    echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM"
+    exit 1
+fi
+exec "$pybinary"  "$0" "${filtered[@]}" # '''
 
 # -*- coding: utf-8 -*-
 # Description:
