stock configs in /usr/lib/netdata (#4283)
* makefiles install configs in /usr/lib/netdata/conf.d; #4182

* stock health config in /usr/lib/netdata/conf.d/health.d

* unit test path concatenation

* simplified health file management

* use stream.conf from stock config if it does not exist in /etc/netdata

* indicate loading of user config in function call

* load netdata.conf from stock dir if not found in /etc/netdata

* added NETDATA_USER_CONFIG_DIR

* provide defaults before loading config

* charts.d uses stock files

* fping now uses the stock config files

* tc-qos-helper.sh now uses stock configs

* cgroup-name.sh now uses stock configs too

* simplified cgroup-name.sh for user and stock config

* alarm-notify.sh uses stock configs too

* simplified fping plugin configs loading

* simplified tc-qos-helper.sh configs loading

* added error handling to charts.d.plugin

* apps.plugin used stock configs

* generalized recursive double-directory configs loading

* statsd uses stock configs

* node.d.plugin uses stock configs

* compile-time decision of netdata default paths for all files

* makeself cleans up old stock config files from user configuration directories

* fixed makeself typo

* netdata-installer.sh removes stock files from user configuration directories

* python.d.plugin user/stock configs update

* cleanup stock config files from /etc/netdata, only once

* python.d.plugin log loaded files

* fix permissions of stock config files and provide an "orig" link for quick access

* create help link on stock configs migration for static installations

* create user config directories

* example statsd synthetic charts now state they are examples

* updated configs.signatures

* spec file

* fixes in spec file

* fix typo

* install netdata after cleaning up stock configs from /etc/netdata

* python.d: add cpuidle stock conf

diff --git a/plugins.d/alarm-notify.sh.in b/plugins.d/alarm-notify.sh.in
--- a/plugins.d/alarm-notify.sh.in
+++ b/plugins.d/alarm-notify.sh.in
@@ -159,9 +159,10 @@ custom_sender() {
 # -----------------------------------------------------------------------------
 # defaults to allow running this script by hand
 
-[ -z "${NETDATA_CONFIG_DIR}"   ] && NETDATA_CONFIG_DIR="$(dirname "${0}")/../../../../etc/netdata"
-[ -z "${NETDATA_CACHE_DIR}"    ] && NETDATA_CACHE_DIR="$(dirname "${0}")/../../../../var/cache/netdata"
-[ -z "${NETDATA_REGISTRY_URL}" ] && NETDATA_REGISTRY_URL="https://registry.my-netdata.io"
+[ -z "${NETDATA_USER_CONFIG_DIR}"  ] && NETDATA_USER_CONFIG_DIR="@configdir_POST@"
+[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="@libconfigdir_POST@"
+[ -z "${NETDATA_CACHE_DIR}"        ] && NETDATA_CACHE_DIR="@cachedir_POST@"
+[ -z "${NETDATA_REGISTRY_URL}"     ] && NETDATA_REGISTRY_URL="https://registry.my-netdata.io"
 
 # -----------------------------------------------------------------------------
 # parse command line parameters
@@ -362,14 +363,20 @@ DEFAULT_RECIPIENT_IRC=
 IRC_NETWORK=
 declare -A role_recipients_irc=()
 
-# load the user configuration
-# this will overwrite the variables above
-if [ -f "${NETDATA_CONFIG_DIR}/health_alarm_notify.conf" ]
-    then
-    source "${NETDATA_CONFIG_DIR}/health_alarm_notify.conf"
-else
-    error "Cannot find file ${NETDATA_CONFIG_DIR}/health_alarm_notify.conf. Using internal defaults."
-fi
+# load the stock and user configuration files
+# these will overwrite the variables above
+
+for CONFIG in "${NETDATA_STOCK_CONFIG_DIR}/health_alarm_notify.conf" "${NETDATA_USER_CONFIG_DIR}/health_alarm_notify.conf"
+do
+    if [ -f "${CONFIG}" ]
+        then
+        debug "Loading config file '${CONFIG}'..."
+        source "${CONFIG}"
+        [ $? -ne 0 ] && error "Failed to load config file '${CONFIG}'."
+    else
+        warning "Cannot find file '${CONFIG}'."
+    fi
+done
 
 # If we didn't autodetect the character set for e-mail and it wasn't
 # set by the user, we need to set it to a reasonable default.  UTF-8
diff --git a/plugins.d/charts.d.plugin.in b/plugins.d/charts.d.plugin.in
--- a/plugins.d/charts.d.plugin.in
+++ b/plugins.d/charts.d.plugin.in
@@ -117,13 +117,14 @@ info "started from '$PROGRAM_FILE' with options: $*"
 # netdata exposes a few environment variables for us
 
 [ -z "${NETDATA_PLUGINS_DIR}" ] && NETDATA_PLUGINS_DIR="$(dirname "${0}")"
-[ -z "${NETDATA_CONFIG_DIR}" ] && NETDATA_CONFIG_DIR="$(dirname "${0}")/../../../../etc/netdata"
+[ -z "${NETDATA_USER_CONFIG_DIR}"  ] && NETDATA_USER_CONFIG_DIR="@configdir_POST@"
+[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="@libconfigdir_POST@"
 
 pluginsd="${NETDATA_PLUGINS_DIR}"
-confd="${NETDATA_CONFIG_DIR}"
+stockconfd="${NETDATA_STOCK_CONFIG_DIR}/${PROGRAM_NAME}"
+userconfd="${NETDATA_USER_CONFIG_DIR}/${PROGRAM_NAME}"
+olduserconfd="${NETDATA_USER_CONFIG_DIR}"
 chartsd="$pluginsd/../charts.d"
-
-myconfig="$confd/$PROGRAM_NAME.conf"
 
 minimum_update_frequency="${NETDATA_UPDATE_EVERY-1}"
 update_every=${minimum_update_frequency}    # this will be overwritten by the command line
@@ -231,22 +232,33 @@ mysleep="sleep"
 # if found and included, this file overwrites loopsleepms()
 # and current_time_ms() with a high resolution timer function
 # for precise looping.
-. "$pluginsd/loopsleepms.sh.inc"
+source "$pluginsd/loopsleepms.sh.inc"
+[ $? -ne 0 ] && error "Failed to load '$pluginsd/loopsleepms.sh.inc'."
 
 # -----------------------------------------------------------------------------
 # load my configuration
 
-if [ -f "$myconfig" ]
+for myconfig in "${NETDATA_STOCK_CONFIG_DIR}/${PROGRAM_NAME}.conf" "${NETDATA_USER_CONFIG_DIR}/${PROGRAM_NAME}.conf"
+do
+    if [ -f "$myconfig" ]
     then
-    . "$myconfig"
-    [ $? -ne 0 ] && fatal "cannot load $myconfig"
+        source "$myconfig"
+        if [ $? -ne 0 ]
+        then
+            error "Config file '$myconfig' loaded with errors."
+        else
+            info "Configuration file '$myconfig' loaded."
+        fi
+    else
+        warning "Configuration file '$myconfig' not found."
+    fi
+done
 
-    time_divisor=$((time_divisor))
-    [ $time_divisor -lt 10 ] && time_divisor=10
-    [ $time_divisor -gt 100 ] && time_divisor=100
-else
-    info "configuration file '$myconfig' not found. Using defaults."
-fi
+# make sure time_divisor is right
+time_divisor=$((time_divisor))
+[ $time_divisor -lt 10 ] && time_divisor=10
+[ $time_divisor -gt 100 ] && time_divisor=100
+
 
 # we check for the timeout command, after we load our
 # configuration, so that the user may overwrite the
@@ -412,7 +424,7 @@ all_enabled_charts() {
 
         if [ ! "${enabled}" = "${required}" ]
         then
-            info "is disabled. Add a line with $chart=$required in $myconfig to enable it (or remove the line that disables it)."
+            info "is disabled. Add a line with $chart=$required in '${NETDATA_USER_CONFIG_DIR}/${PROGRAM_NAME}.conf' to enable it (or remove the line that disables it)."
         else
             debug "is enabled for auto-detection."
             local charts="$charts $chart"
@@ -448,18 +460,18 @@ all_enabled_charts() {
         fi
 
         # check its config
-        #if [ -f "$confd/$chart.conf" ]
+        #if [ -f "$userconfd/$chart.conf" ]
         #then
-        #   if [ ! -z "$( cat "$confd/$chart.conf" | sed "s/^ \+//g" | grep -v "^$" | grep -v "^#" | grep -v "^$chart$charts_undescore" )" ]
+        #   if [ ! -z "$( cat "$userconfd/$chart.conf" | sed "s/^ \+//g" | grep -v "^$" | grep -v "^#" | grep -v "^$chart$charts_undescore" )" ]
         #   then
-        #       error "module's $chart config $confd/$chart.conf should only have lines starting with $chart$charts_undescore . Disabling it."
+        #       error "module's $chart config $userconfd/$chart.conf should only have lines starting with $chart$charts_undescore . Disabling it."
         #       continue
         #   fi
         #fi
 
         #if [ $dryrunner -eq 1 ]
         #   then
-        #   "$pluginsd/charts.d.dryrun-helper.sh" "$chart" "$chartsd/$chart.chart.sh" "$confd/$chart.conf" >/dev/null
+        #   "$pluginsd/charts.d.dryrun-helper.sh" "$chart" "$chartsd/$chart.chart.sh" "$userconfd/$chart.conf" >/dev/null
         #   if [ $? -ne 0 ]
         #   then
         #       error "module's $chart did not pass the dry run check. This means it uses global variables not starting with $chart. Disabling it."
@@ -487,18 +499,35 @@ do
 
     debug "loading module: '$chartsd/$chart.chart.sh'"
 
-    . "$chartsd/$chart.chart.sh"
+    source "$chartsd/$chart.chart.sh"
+    [ $? -ne 0 ] && warning "Module '$chartsd/$chart.chart.sh' loaded with errors."
 
-    if [ -f "$confd/$PROGRAM_NAME/$chart.conf" ]
+    # first load the stock config
+    if [ -f "$stockconfd/$chart.conf" ]
     then
-        debug "loading module configuration: '$confd/$PROGRAM_NAME/$chart.conf'"
-        . "$confd/$PROGRAM_NAME/$chart.conf"
-    elif [ -f "$confd/$chart.conf" ]
-    then
-        debug "loading module configuration: '$confd/$chart.conf'"
-        . "$confd/$chart.conf"
+        debug "loading module configuration: '$stockconfd/$chart.conf'"
+        source "$stockconfd/$chart.conf"
+        [ $? -ne 0 ] && warning "Config file '$stockconfd/$chart.conf' loaded with errors."
     else
-        warning "configuration file '$confd/$PROGRAM_NAME/$chart.conf' not found. Using defaults."
+        debug "not found module configuration: '$stockconfd/$chart.conf'"
+    fi
+
+    # then load the user config (it overwrites the stock)
+    if [ -f "$userconfd/$chart.conf" ]
+    then
+        debug "loading module configuration: '$userconfd/$chart.conf'"
+        source "$userconfd/$chart.conf"
+        [ $? -ne 0 ] && warning "Config file '$userconfd/$chart.conf' loaded with errors."
+    else
+        debug "not found module configuration: '$userconfd/$chart.conf'"
+
+        if [ -f "$olduserconfd/$chart.conf" ]
+        then
+            # support for very old netdata that had the charts.d module configs in /etc/netdata
+            info "loading module configuration from obsolete location: '$olduserconfd/$chart.conf'"
+            source "$olduserconfd/$chart.conf"
+            [ $? -ne 0 ] && warning "Config file '$olduserconfd/$chart.conf' loaded with errors."
+        fi
     fi
 
     eval "dt=\$$chart$suffix_update_every"
