fixed typo

diff --git a/python.d/python-modules-installer.sh.in b/python.d/python-modules-installer.sh.in
--- a/python.d/python-modules-installer.sh.in
+++ b/python.d/python-modules-installer.sh.in
@@ -63,7 +63,7 @@ fi
 [ -z "${pip}" ] && pip="$(which pip 2>/dev/null)"
 if [ -z "${pip}" ]
 then
-    echo >& "pip command is required to install python v${pv} modules"
+    echo >&2 "pip command is required to install python v${pv} modules"
     exit 1
 fi
 
