Add a failsafe in case fail to set the cap_perfmon
Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>

diff --git a/contrib/debian/netdata-plugin-perf.postinst b/contrib/debian/netdata-plugin-perf.postinst
--- a/contrib/debian/netdata-plugin-perf.postinst
+++ b/contrib/debian/netdata-plugin-perf.postinst
@@ -8,7 +8,9 @@ case "$1" in
     chmod 0750 /usr/libexec/netdata/plugins.d/perf.plugin
 
     if capsh --supports=cap_perfmon 2>/dev/null; then
-        setcap cap_perfmon+ep /usr/libexec/netdata/plugins.d/perf.plugin
+        if ! setcap cap_perfmon+ep /usr/libexec/netdata/plugins.d/perf.plugin; then
+            echo "Failed to set cap_perfmon capability, trying fallback. . ."
+        fi
     else
         if ! setcap cap_sys_admin+ep /usr/libexec/netdata/plugins.d/perf.plugin; then
             chmod -f 4750 /usr/libexec/netdata/plugins.d/perf.plugin
