Fix workflow
Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>

diff --git a/contrib/debian/netdata-plugin-perf.postinst b/contrib/debian/netdata-plugin-perf.postinst
--- a/contrib/debian/netdata-plugin-perf.postinst
+++ b/contrib/debian/netdata-plugin-perf.postinst
@@ -7,12 +7,11 @@ case "$1" in
     chown root:netdata /usr/libexec/netdata/plugins.d/perf.plugin
     chmod 0750 /usr/libexec/netdata/plugins.d/perf.plugin
 
-    if capsh --supports=cap_perfmon 2>/dev/null; then
-        if ! setcap cap_perfmon+ep /usr/libexec/netdata/plugins.d/perf.plugin; then
-            echo "Failed to set cap_perfmon capability, trying fallback. . ."
-        fi
+    if ! setcap cap_perfmon+ep /usr/libexec/netdata/plugins.d/perf.plugin; then
+        echo "Set cap_perfmon capabilties for perf.plugin"
     else
         if ! setcap cap_sys_admin+ep /usr/libexec/netdata/plugins.d/perf.plugin; then
+            echo "Failed to setup capabilties for perf.plugin, setting setuid"
             chmod -f 4750 /usr/libexec/netdata/plugins.d/perf.plugin
         fi
     fi
