normalize error code

diff --git a/claim/netdata-claim.sh.in b/claim/netdata-claim.sh.in
--- a/claim/netdata-claim.sh.in
+++ b/claim/netdata-claim.sh.in
@@ -83,6 +83,8 @@ ERROR_MESSAGES[16]="Gateway Timeout"
 ERROR_KEYS[17]="ErrServiceUnavailable"
 ERROR_MESSAGES[17]="Service Unavailable"
 
+# Exit code: 18 - Agent unique id is not generated yet.
+
 get_config_value() {
     conf_file="${1}"
     section="${2}"
@@ -145,7 +147,7 @@ if [ -r "${MACHINE_GUID_FILE}" ]; then
         MGUID=$ID
 else
         echo >&2 "netdata.public.unique.id is not generated yet. Please run agent at least once before attempting to claim. Agent generates this file on first startup."
-        exit 22
+        exit 18
 fi
 
 # get token from file
