Added read-config command to the CLI tool.
This works on any configuration option.

Changed the placement of the specific options that we need to access via -W get, this can
retrieve the defaults for
    global/run as user
    global/netdata cloud
    cloud/cloud base url

diff --git a/claim/netdata-claim.sh.in b/claim/netdata-claim.sh.in
--- a/claim/netdata-claim.sh.in
+++ b/claim/netdata-claim.sh.in
@@ -102,9 +102,9 @@ fi
 get_config_value() {
     section="${1}"
     key_name="${2}"
-    config_result=$(@sbindir_POST@/netdatacli 2>/dev/null read-config "$section" "$key_name")
-    if [ $? != 0 ]; then
-       echo "cli failed, manual attempt"
+    config_result=$(@sbindir_POST@/netdatacli 2>/dev/null read-config "$section|$key_name"; exit $?)
+    if [ "$?" != "0" ]; then
+       echo "cli failed ($?, $config_result), manual attempt"
        config_result=$(@sbindir_POST@/netdata 2>/dev/null -W get "$section" "$key_name" unknown_default)
     fi
 }
