Claiming script pulls defaults from the netdata installation

diff --git a/claim/netdata-claim.sh.in b/claim/netdata-claim.sh.in
--- a/claim/netdata-claim.sh.in
+++ b/claim/netdata-claim.sh.in
@@ -77,6 +77,16 @@
 # Error message: "Service Unavailable"
 # Exit code: 15
 
+get_config_value() {
+    section="${1}"
+    key_name="${2}"
+    config_result=$(@sbindir_POST@/netdatacli 2>/dev/null read-config "$section|$key_name"; exit $?)
+    if [ "$?" != "0" ]; then
+       echo 2> "cli failed, assume netdata is not running and query the on-disk config"
+       config_result=$(@sbindir_POST@/netdata 2>/dev/null -W get "$section" "$key_name" unknown_default)
+    fi
+    echo $config_result
+}
 if command -v curl >/dev/null 2>&1 ; then
         URLTOOL="curl"
 elif command -v wget >/dev/null 2>&1 ; then
@@ -99,20 +109,6 @@ if [ "@can_enable_aclk_POST@" != "yes" ]; then
     exit 3
 fi
 
-get_config_value() {
-    section="${1}"
-    key_name="${2}"
-    config_result=$(@sbindir_POST@/netdatacli 2>/dev/null read-config "$section|$key_name"; exit $?)
-    if [ "$?" != "0" ]; then
-       echo "cli failed ($?, $config_result), manual attempt"
-       config_result=$(@sbindir_POST@/netdata 2>/dev/null -W get "$section" "$key_name" unknown_default)
-    fi
-}
-
-get_config_value global "run as user"
-echo "Netdata user: $config_result"
-exit 0
-
 # -----------------------------------------------------------------------------
 # defaults to allow running this script by hand
 
@@ -120,7 +116,7 @@ exit 0
 MACHINE_GUID_FILE="@registrydir_POST@/netdata.public.unique.id"
 CLAIMING_DIR="${NETDATA_USER_CONFIG_DIR}/claim.d"
 TOKEN="unknown"
-URL_BASE="https://netdata.cloud"
+URL_BASE=$(get_config_value cloud "cloud base url")
 ID="unknown"
 ROOMS=""
 [ -z "$HOSTNAME" ] && HOSTNAME=$(hostname)
@@ -128,13 +124,8 @@ CLOUD_CERTIFICATE_FILE="${CLAIMING_DIR}/cloud_fullchain.pem"
 VERBOSE=0
 INSECURE=0
 RELOAD=1
-NETDATA_USER=netdata
+NETDATA_USER=$(get_config_value global "run as user")
 [ -z "$EUID" ] && EUID="$(id -u)"
-
-CONF_USER=$(grep '^[ 	#]*run as user[ 	]*=' "${NETDATA_USER_CONFIG_DIR}/netdata.conf" 2>/dev/null)
-if [ -n "$CONF_USER" ]; then
-    NETDATA_USER=$(echo "$CONF_USER" | sed 's/^[^=]*=[ \t]*//' | sed 's/[ \t]*$//')
-fi
 
 
 # get the MACHINE_GUID by default
@@ -190,6 +181,8 @@ echo >&2 "Rooms: $ROOMS"
 echo >&2 "Hostname: $HOSTNAME"
 echo >&2 "Proxy: $PROXY"
 echo >&2 "Netdata user: $NETDATA_USER"
+
+exit 0
 
 # create the claiming directory for this user
 if [ ! -d "${CLAIMING_DIR}" ] ; then
