Fix typo

diff --git a/claim/netdata-claim.sh.in b/claim/netdata-claim.sh.in
--- a/claim/netdata-claim.sh.in
+++ b/claim/netdata-claim.sh.in
@@ -110,12 +110,12 @@ fi
 
 # shellcheck disable=SC2050
 if [ "@enable_cloud_POST@" = "no" ]; then
-    echo >&2 "This agent was build with --disable-cloud and cannot be claimed"
+    echo >&2 "This agent was built with --disable-cloud and cannot be claimed"
     exit 3
 fi
 # shellcheck disable=SC2050
 if [ "@can_enable_aclk_POST@" != "yes" ]; then
-    echo >&2 "This agent was build without the dependencies for Cloud and cannot be claimed"
+    echo >&2 "This agent was built without the dependencies for Cloud and cannot be claimed"
     exit 3
 fi
 
