Query systemd for unit file paths on install/uninstall.
This makes our installation code more portable and more concise, and
should make the uninstallation code significantly more robust.

Also includes a number of other improvements to systemd handling and
updater handling in the uninstaller that should make it much more
thorough and reliable.

diff --git a/system/install-service.sh.in b/system/install-service.sh.in
--- a/system/install-service.sh.in
+++ b/system/install-service.sh.in
@@ -236,16 +236,25 @@ check_systemd() {
 }
 
 get_systemd_service_dir() {
-  if [ -w "/lib/systemd/system" ]; then
-    echo "/lib/systemd/system"
-  elif [ -w "/usr/lib/systemd/system" ]; then
-    echo "/usr/lib/systemd/system"
-  elif [ -w "/etc/systemd/system" ]; then
-    echo "/etc/systemd/system"
-  else
-    error "Unable to detect systemd service directory."
-    exit 4
-  fi
+  set +e
+  unit_paths="$(systemctl show -p UnitPath --value | tr ' ' '\n')"
+  set -e
+
+  # The strange `sed` expression here reverses line order (systemd lists
+  # unit paths in descending priority, we want to check the lib paths in
+  # ascending priority)
+  lib_paths="$(echo "${unit_paths}" | grep -vE '^/\(run|etc\)' | sed '1!x;H;1h;$!d;g')"
+  etc_paths="$(echo "${unit_paths}" | grep -E '^/etc' | grep -vE '(attached|control)$')"
+
+  for path in ${lib_paths} ${etc_paths}; do
+    if [ -d "${path}" ] && [ -w "${path}" ]; then
+      echo "${path}"
+      return 0
+    fi
+  done
+
+  error "Unable to detect usable systemd service directory."
+  exit 4
 }
 
 install_systemd_service() {
