health_connection: shell script
Finilize the shell script to test the PR

diff --git a/tests/template_dimension/template_dim.sh.in b/tests/template_dimension/template_dim.sh.in
--- a/tests/template_dimension/template_dim.sh.in
+++ b/tests/template_dimension/template_dim.sh.in
@@ -1,3 +1,84 @@
 #!/bin/bash
 
-#Use all the files in this directory to send the message
+#The health directory to put the alarms
+HEALTHDIR="@configdir_POST@/health.d/"
+
+#the current time
+OUTDIR="alarms/"
+MURL="http://localhost:19999/api/v1/alarms?active"
+
+#error messages
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NOCOLOR='\033[0m'
+
+SYSTEMALARM="dev_dim_template_system"
+USERALARM="dev_dim_template_user"
+
+change_alarm_file() {
+  if [ -f "$1" ]; then
+    rm "$1"
+  fi
+
+  #copy keeping the permissions
+  cp -a "$2" "$3"
+}
+
+netdata_test_download() {
+   grep "HTTP/1.1 200 OK" "$1" 2>/dev/null 1>/dev/null
+   TEST="$?"
+   if [ "$TEST" -ne "0" ]; then
+     echo "${RED} Error to get the alarm log."
+     exit 1
+   fi
+
+   TOTSYS=$(grep  -w "$SYSTEMALARM" "$2" | grep name | cut -d: -f2 | grep -c "$SYSTEMALARM")
+   TOTUSER=$(grep  -w "$USERALARM" "$2" | grep name | cut -d: -f2 | grep -c "$USERALARM")
+
+   if [ "$TOTSYS" -ne "1" ]; then
+     echo "${RED} The number of actives alarms with the name $SYSTEMALARM is wrong"
+     exit 1
+   fi
+
+   if [ "$TOTUSER" -ne "1" ]; then
+     echo "${RED} The number of actives alarms with the name $SYSTEMUSER is wrong"
+     exit 1
+   fi
+}
+
+get_the_logs() {
+  curl -v -k --create-dirs -o "$OUTDIR/$1.out" "$MURL" 2> "$OUTDIR/$1.err"
+  netdata_test_download "$OUTDIR/$1.err" "$OUTDIR/$1.out"
+}
+
+process_data() {
+  netdata
+  echo -e "${NOCOLOR}Sleeping during 15 seconds to create alarms"
+  sleep 15
+  killall netdata
+  get_the_logs "$1"
+}
+
+mkdir "$OUTDIR"
+CREATEDIR="$?"
+if [ "$CREATEDIR" -ne "0" ]; then
+  echo  -e "${RED}Cannot create the output directory"
+  exit 1
+fi
+
+change_alarm_file "./0" "system_cpu.conf.unique_alarm" "$HEALTHDIR/dim_double_without_template.conf"
+process_data "double_without_template"
+
+change_alarm_file "$HEALTHDIR/dim_double_without_template.conf" "system_cpu.conf.alarm_foreach" "$HEALTHDIR/dim_foreach_without_template.conf"
+process_data "foreach_without_template"
+
+change_alarm_file "$HEALTHDIR/dim_foreach_without_template.conf" "system_cpu.conf.template_alarm" "$HEALTHDIR/dim_double_with_template.conf"
+process_data "double_with_template"
+
+change_alarm_file "$HEALTHDIR/dim_double_with_template.conf" "system_cpu.conf.template_foreach" "$HEALTHDIR/dim_foreach_with_template.conf"
+process_data "foreach_with_template"
+
+rm "$HEALTHDIR/dim_foreach_with_template.conf"
+rm -rf "$OUTDIR"
+
+echo  -e "${GREEN} all the tests were sucessful"
