health_connection: Functional test review
After to review the functional test script, it was necessary to small adjust to
test all the features available with the new version

diff --git a/tests/template_dimension/template_dim.sh.in b/tests/template_dimension/template_dim.sh.in
--- a/tests/template_dimension/template_dim.sh.in
+++ b/tests/template_dimension/template_dim.sh.in
@@ -4,16 +4,16 @@
 HEALTHDIR="@configdir_POST@/health.d/"
 
 #the current time
-OUTDIR="alarms/"
-MURL="http://localhost:19999/api/v1/alarms?active"
+OUTDIR="alarms"
+QUERY="/api/v1/alarms?all"
+MURL="http://localhost:19999$QUERY"
 
 #error messages
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 NOCOLOR='\033[0m'
 
-SYSTEMALARM="dev_dim_template_system"
-USERALARM="dev_dim_template_user"
+ALARMTEST="dev_dim_template"
 
 change_alarm_file() {
   if [ -f "$1" ]; then
@@ -28,27 +28,21 @@ netdata_test_download() {
    grep "HTTP/1.1 200 OK" "$1" 2>/dev/null 1>/dev/null
    TEST="$?"
    if [ "$TEST" -ne "0" ]; then
-     echo "${RED} Error to get the alarm log."
-     exit 1
+      echo -e "${RED} Error to get the alarm log."
+      exit 1
    fi
 
-   TOTSYS=$(grep  -w "$SYSTEMALARM" "$2" | grep name | cut -d: -f2 | grep -c "$SYSTEMALARM")
-   TOTUSER=$(grep  -w "$USERALARM" "$2" | grep name | cut -d: -f2 | grep -c "$USERALARM")
+   TOTALARM=$(grep "$ALARMTEST" "$2" | grep name | cut -d: -f2 | grep -c "$ALARMTEST")
 
-   if [ "$TOTSYS" -ne "1" ]; then
-     echo "${RED} The number of actives alarms with the name $SYSTEMALARM is wrong"
+  if [ "$TOTALARM" -ne "$3" ]; then
+     echo -e "${RED} The number of actives alarms with the name $SYSTEMALARM is wrong"
      exit 1
-   fi
-
-   if [ "$TOTUSER" -ne "1" ]; then
-     echo "${RED} The number of actives alarms with the name $SYSTEMUSER is wrong"
-     exit 1
-   fi
+  fi
 }
 
 get_the_logs() {
   curl -v -k --create-dirs -o "$OUTDIR/$1.out" "$MURL" 2> "$OUTDIR/$1.err"
-  netdata_test_download "$OUTDIR/$1.err" "$OUTDIR/$1.out"
+  netdata_test_download "$OUTDIR/$1.err" "$OUTDIR/$1.out" $2
 }
 
 process_data() {
@@ -56,7 +50,7 @@ process_data() {
   echo -e "${NOCOLOR}Sleeping during 15 seconds to create alarms"
   sleep 15
   killall netdata
-  get_the_logs "$1"
+  get_the_logs "$1" $2
 }
 
 mkdir "$OUTDIR"
@@ -65,23 +59,27 @@ if [ "$CREATEDIR" -ne "0" ]; then
   echo  -e "${RED}Cannot create the output directory, it already exists. The test will overwrite previous results."
 fi
 
+if [ ! -z "$1" ]; then
+  MURL="$1$QUERY"
+fi
+
 change_alarm_file "./0" "system_cpu.conf.unique_alarm" "$HEALTHDIR/dim_double_without_template.conf"
-process_data "double_without_template"
+process_data "double_without_template" 3 "$HEALTHDIR/dim_double_without_template.conf"
 
 change_alarm_file "$HEALTHDIR/dim_double_without_template.conf" "system_cpu.conf.alarm_foreach" "$HEALTHDIR/dim_foreach_without_template.conf"
-process_data "foreach_without_template"
+process_data "foreach_without_template" 3 "$HEALTHDIR/dim_foreach_without_template.conf"
 
 change_alarm_file "$HEALTHDIR/dim_foreach_without_template.conf" "system_cpu.conf.alarm_foreach_sp" "$HEALTHDIR/dim_foreach_without_template_sp.conf"
-process_data "foreach_without_template"
+process_data "foreach_without_template" 10 "$HEALTHDIR/dim_foreach_without_template_sp.conf"
 
 change_alarm_file "$HEALTHDIR/dim_foreach_without_template_sp.conf" "system_cpu.conf.template_alarm" "$HEALTHDIR/dim_double_with_template.conf"
-process_data "double_with_template"
+process_data "double_with_template" 3 "$HEALTHDIR/dim_double_with_template.conf"
 
 change_alarm_file "$HEALTHDIR/dim_double_with_template.conf" "system_cpu.conf.template_foreach" "$HEALTHDIR/dim_foreach_with_template.conf"
-process_data "foreach_with_template"
+process_data "foreach_with_template" 3 "$HEALTHDIR/dim_foreach_with_template.conf"
 
 change_alarm_file "$HEALTHDIR/dim_foreach_with_template.conf" "system_cpu.conf.template_foreach_sp" "$HEALTHDIR/dim_foreach_with_template_sp.conf"
-process_data "foreach_with_template"
+process_data "foreach_with_template" 10 "$HEALTHDIR/dim_foreach_with_template_sp.conf"
 
 rm "$HEALTHDIR/dim_foreach_with_template_sp.conf"
 rm -rf "$OUTDIR"
