Hangouts

diff --git a/health/notifications/alarm-notify.sh.in b/health/notifications/alarm-notify.sh.in
--- a/health/notifications/alarm-notify.sh.in
+++ b/health/notifications/alarm-notify.sh.in
@@ -145,6 +145,7 @@ docurl() {
 
 method_names="
 email
+hangouts
 pushover
 pushbullet
 telegram
@@ -182,9 +183,9 @@ fi
 # -----------------------------------------------------------------------------
 # defaults to allow running this script by hand
 
-[ -z "${NETDATA_USER_CONFIG_DIR}" ] && NETDATA_USER_CONFIG_DIR="@configdir_POST@"
-[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="@libconfigdir_POST@"
-[ -z "${NETDATA_CACHE_DIR}" ] && NETDATA_CACHE_DIR="@cachedir_POST@"
+[ -z "${NETDATA_USER_CONFIG_DIR}" ] && NETDATA_USER_CONFIG_DIR="/etc/netdata"
+[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="/usr/lib/netdata/conf.d"
+[ -z "${NETDATA_CACHE_DIR}" ] && NETDATA_CACHE_DIR="/var/cache/netdata"
 [ -z "${NETDATA_REGISTRY_URL}" ] && NETDATA_REGISTRY_URL="https://registry.my-netdata.io"
 
 # -----------------------------------------------------------------------------
@@ -280,6 +281,9 @@ done
 for method_name in ${method_names}; do
 	declare -A role_recipients_${method_name}
 done
+
+# hangouts configs
+HANGOUTS_WEBHOOK_URL=
 
 # slack configs
 SLACK_WEBHOOK_URL=
@@ -447,6 +451,9 @@ filter_recipient_by_criticality() {
 # check slack
 [ -z "${SLACK_WEBHOOK_URL}" ] && SEND_SLACK="NO"
 
+# check hangouts
+[ -z "${HANGOUTS_WEBHOOK_URL}" ] && SEND_HANGOUTS="NO"
+
 # check rocketchat
 [ -z "${ROCKETCHAT_WEBHOOK_URL}" ] && SEND_ROCKETCHAT="NO"
 
@@ -492,6 +499,7 @@ filter_recipient_by_criticality() {
 
 if [ "${SEND_PUSHOVER}" = "YES" ] ||
 	[ "${SEND_SLACK}" = "YES" ] ||
+	[ "${SEND_HANGOUTS}" = "YES" ] ||
 	[ "${SEND_ROCKETCHAT}" = "YES" ] ||
 	[ "${SEND_ALERTA}" = "YES" ] ||
 	[ "${SEND_PD}" = "YES" ] ||
@@ -520,6 +528,7 @@ if [ "${SEND_PUSHOVER}" = "YES" ] ||
 		SEND_SLACK="NO"
 		SEND_MSTEAM="NO"
 		SEND_ROCKETCHAT="NO"
+		SEND_HANGOUTS="NO"
 		SEND_ALERTA="NO"
 		SEND_PD="NO"
 		SEND_FLOCK="NO"
@@ -631,6 +640,7 @@ for method in "${SEND_EMAIL}" \
 	"${SEND_PUSHOVER}" \
 	"${SEND_TELEGRAM}" \
 	"${SEND_SLACK}" \
+	"${SEND_HANGOUTS}" \
 	"${SEND_ROCKETCHAT}" \
 	"${SEND_ALERTA}" \
 	"${SEND_FLOCK}" \
@@ -790,6 +800,107 @@ send_email() {
 			return 1
 		fi
 	fi
+
+	return 1
+}
+
+# -----------------------------------------------------------------------------
+# hangouts sender
+
+send_hangouts() {
+	local webhook="${1}" channels="${2}" httpcode sent=0 channel color payload
+
+	[ "${SEND_HANGOUTS}" != "YES" ] && return 1
+
+	case "${status}" in
+	WARNING) color="#ffa700" ;;
+	CRITICAL) color="#d62d20" ;;
+	CLEAR) color="#008744" ;;
+	*) color="#777777" ;;
+	esac
+
+	for channel in ${channels}; do
+	payload="$(
+		cat <<EOF
+		{
+			"cards": [
+				{
+					"header": {
+						"title": "Netdata on<br>${host}",
+						"imageUrl": "${images_base_url}/images/banner-icon-144x144.png",
+						"imageStyle": "IMAGE"
+					},
+					"sections": [
+						{
+							"header": "<b>${host}</b>",
+							"widgets": [
+								{
+									"keyValue": {
+										"topLabel": "Status Message",
+										"content": "<b>${status_message}</b>",
+										"contentMultiline": "true",
+										"iconUrl": "${image}",
+										"onClick": {
+											"openLink": {
+												"url": "${goto_url}"
+											}
+										}
+									}
+								},
+								{
+									"keyValue": {
+										"topLabel": "${chart} | ${family}",
+										"content": "<font color=${color}>${alarm}</font>",
+										"contentMultiline": "true"
+									}
+								}
+							]
+						},
+						{
+							"widgets": [
+								{
+									"textParagraph": {
+									"text": "<font color=\"#0057e7\">@ ${date}\n<b>${info}</b></font>"
+									}
+								}
+							]
+						},
+						{
+							"widgets": [
+								{
+									"buttons": [
+										{
+											"textButton": {
+												"text": "Go to ${host}",
+												"onClick": {
+													"openLink": {
+														"url": "http://${host}:19999/"
+													}
+												}
+											}
+										}
+									]
+								}
+							]
+						}
+					]
+				}
+			]
+		}
+EOF
+	)"
+
+	httpcode=$(docurl -H "Content-Type: application/json" -X POST -d "${payload}" "${webhook}")
+
+	if [ "${httpcode}" = "200" ]; then
+		info "sent hangouts notification for: ${host} ${chart}.${name} is ${status} to '${channel}'"
+		sent=$((sent + 1))
+	else
+		error "failed to send hangouts notification for: ${host} ${chart}.${name} is ${status} to '${channel}', with HTTP error code ${httpcode}."
+	fi
+	done
+
+	[ ${sent} -gt 0 ] && return 0
 
 	return 1
 }
@@ -1742,8 +1853,8 @@ GOTOCLOUD=0
 
 if [ "${NETDATA_REGISTRY_URL}" == "https://registry.my-netdata.io" ]; then
 	if [ -z "${NETDATA_REGISTRY_UNIQUE_ID}" ]; then
-		if [ -f "@registrydir_POST@/netdata.public.unique.id" ]; then
-			NETDATA_REGISTRY_UNIQUE_ID="$(cat "@registrydir_POST@/netdata.public.unique.id")"
+		if [ -f "/var/lib/netdata/registry/netdata.public.unique.id" ]; then
+			NETDATA_REGISTRY_UNIQUE_ID="$(cat "/var/lib/netdata/registry/netdata.public.unique.id")"
 		fi
 	fi
 	if [ ! -z "${NETDATA_REGISTRY_UNIQUE_ID}" ]; then
@@ -1841,6 +1952,16 @@ raised_for_html=
 
 send_slack "${SLACK_WEBHOOK_URL}" "${to_slack}"
 SENT_SLACK=$?
+
+# -----------------------------------------------------------------------------
+# send the hangouts notification
+
+# hangouts aggregates posts from the same username
+# so we use "${host} ${status}" as the bot username, to make them diff
+
+send_hangouts "${HANGOUTS_WEBHOOK_URL}" "${to_hangouts}"
+SENT_HANGOUTS=$?
+
 
 # -----------------------------------------------------------------------------
 # send the Microsoft notification
@@ -2191,6 +2312,7 @@ for state in "${SENT_EMAIL}" \
 	"${SENT_TELEGRAM}" \
 	"${SENT_SLACK}" \
 	"${SENT_ROCKETCHAT}" \
+	"${SEND_HANGOUTS}" \
 	"${SENT_ALERTA}" \
 	"${SENT_FLOCK}" \
 	"${SENT_DISCORD}" \
