Update .github/dockerfiles/Dockerfile.build_test
Co-Authored-By: Konstantinos Natsakis <5933427+knatsakis@users.noreply.github.com>

diff --git a/.github/dockerfiles/Dockerfile.build_test b/.github/dockerfiles/Dockerfile.build_test
--- a/.github/dockerfiles/Dockerfile.build_test
+++ b/.github/dockerfiles/Dockerfile.build_test
@@ -4,7 +4,7 @@ FROM ${BASE}
 
 ARG PRE
 
-RUN /bin/sh -c 'if [ -n "${PRE}" ]; then /bin/sh -c "${PRE}"; if [ $? -ne 0 ]; then printf "ERROR: PRE failed:\n%s\n" "${PRE}"; exit 1; fi; fi'
+RUN if [ -n "${PRE}" ]; then /bin/sh -c "${PRE}"; if [ $? -ne 0 ]; then printf "ERROR: PRE failed:\n%s\n" "${PRE}"; exit 1; fi; fi
 
 WORKDIR /netdata
 COPY . .
