Control files for netdata package

diff --git a/packaging/cmake/control/netdata/postinst b/packaging/cmake/control/netdata/postinst
--- a/packaging/cmake/control/netdata/postinst
+++ b/packaging/cmake/control/netdata/postinst
@@ -28,13 +28,22 @@ case "$1" in
 
     grep /usr/libexec/netdata /var/lib/dpkg/info/netdata.list | xargs -n 30 chown root:netdata
 
-    for f in ndsudo cgroup-network local-listeners ioping network-viewer.plugin; do
+    # TODO: Ask Austin to review this.
+    for f in ndsudo cgroup-network local-listeners ioping.plugin network-viewer.plugin; do
         chmod 4750 "/usr/libexec/netdata/plugins.d/${f}" || true
     done
 
     ;;
 esac
 
-#DEBHELPER#
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	deb-systemd-helper unmask 'netdata.service' >/dev/null || true
+
+	if deb-systemd-helper --quiet was-enabled 'netdata.service'; then
+		deb-systemd-helper enable 'netdata.service' >/dev/null || true
+	else
+		deb-systemd-helper update-state 'netdata.service' >/dev/null || true
+	fi
+fi
 
 exit 0
