Removed other web servers

diff --git a/tests/health_mgmtapi/health-cmdapi-test.sh.in b/tests/health_mgmtapi/health-cmdapi-test.sh.in
--- a/tests/health_mgmtapi/health-cmdapi-test.sh.in
+++ b/tests/health_mgmtapi/health-cmdapi-test.sh.in
@@ -17,7 +17,8 @@ printhelp () {
 check () {
 	echo -e "${GRAY}Check: '${1}' in 2 sec"
 	sleep 2
-	r=$(curl -s "http://$URL/api/v1/alarms?all" | \
+	resp=$(curl -s "http://$URL/api/v1/alarms?all")
+	r=$(echo "${resp}" | \
 	python3 -c "import sys, json; d=json.load(sys.stdin); \
 	print(\
 	d['alarms']['example.random.example_alarm1']['disabled'], \
@@ -27,8 +28,10 @@ check () {
 	d['alarms']['system.load.load_trigger']['disabled'], \
 	d['alarms']['system.load.load_trigger']['silenced'], \
 	);" 2>&1)
-	
-	if [ "${r}" != "${2}" ] ; then
+	if [ $? -ne 0 ] ; then
+		echo -e "${RED}ERROR: Unexpected response '$resp'"
+		err=$((err+1))
+	elif [ "${r}" != "${2}" ] ; then
 		echo -e "${RED}ERROR: 'Got ${r}'. Expected '${2}'"
 		err=$((err+1))
 	else
